server:
  port: 8083

spring:
  application:
    name: wallet-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5435/wallet_db}
    username: ${SPRING_DATASOURCE_USERNAME:flowpay}
    password: ${SPRING_DATASOURCE_PASSWORD:flowpay}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: health,info
